### ISSUE TITLE
Amount of icons protruding from the button, title bar in recents showing incorrect color.

### ISSUE THREAD

**Issue by DarinMenezes** [afollestad/polar-dashboard#111]
I'm having a couple of problems

1. The text of the amount (if it is a double digit number or more) glitches out the button

![screenshot_20160503-191119](https://cloud.githubusercontent.com/assets/1820165/14990907/89ee5196-1124-11e6-8eff-cd47a072b874.png)

2. The Name Thingy of Recents Shows the color of the light themes primary color, Even if the light themes disabled﻿ and/or the dark theme is the default...

![screenshot_20160503-192157](https://cloud.githubusercontent.com/assets/1820165/14990908/8cc51120-1124-11e6-9459-1e9c85560911.png)

**Comment by afollestad** [comment]
@DarinMenezes thanks!

For future reference, you can drag images into your comment to attach them 😉

The first issue is mostly specific to you, no one else has had that issue. But I'll see what I can do when I have some time.

**Comment by zdunex25** [comment]
I can confirm the 1st one, but for me it happens only if number is 3 digits long, starting form a hundret.

**Comment by afollestad** [comment]
I can't reproduce the cut off button issue on my Nexus 6P, even if I manually set the counter to 1,000,000. But I made some updates to hopefully prevent any issues you could possibly have there.

Also, I fixed the recents theming issue.

**Comment by werdna3232** [comment]
I, too have the cut-off button issue on a Nexus 6p for 2- and 3-digit numbers...
![tkyotsq](https://cloud.githubusercontent.com/assets/18607205/15455638/388d1a92-2017-11e6-8c38-1d70b326046d.jpg)

**Comment by zdunex25** [comment]
I can confirm it still happens, does not move counter to the 2nd line, but text is cut off both sides now.

https://drive.google.com/file/d/0B1ASe-2TlWPjaVhjRlcwdDk1RTg/view?usp=sharing

**Comment by afollestad** [comment]
There are existing updated icon packs such as this one which do not have this problem:

![screener_20160526 11-49-49](https://cloud.githubusercontent.com/assets/1820165/15582754/35fbee42-2338-11e6-8264-f52c38764a51.png)

**Comment by werdna3232** [comment]
Have to agree with @zdunex25. The fix committed did solve the issue previous issue but now some amounts over 3 digits seem to have the same issue. See the photo below. Thanks for your amazing work on Polar so far.
![screenshot_2016-05-30-21-09-09](https://cloud.githubusercontent.com/assets/18607205/15662254/20d4107c-26ac-11e6-9cfa-862fd57149a6.png)

**Comment by afollestad** [comment]
Please try the latest changes
